default: &default
  adapter: postgresql
  encoding: utf8
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  database: evvnt_challenge_dev
  username: mvp
  password: secret
test:
  <<: *default
  database: evvnt_challenge_test
  username: mvp
  password: secret
production:
  <<: *default
  database: evvnt_challenges_prod
  username: mvp
  password: secret